apiVersion: v1
kind: PersistentVolume
metadata:
  name: znc-pv
spec:
  capacity:
    storage: 500M
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /tmp/znc_storage
