apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: znc-cluster-app
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
      openshift.io/image.dockerRepositoryCheck: 2016-08-18T18:49:29Z
    creationTimestamp: null
    generation: 2
    labels:
      app: znc-cluster-app
    name: znc-cluster-app
  spec:
    tags:
    - annotations:
        openshift.io/imported-from: nhripps/znc-cluster-app:latest
      from:
        kind: DockerImage
        name: 172.30.195.154:5000/myproject/znc-cluster-app:latest
      generation: 2
      importPolicy: {}
      name: latest
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    generation: 2
    labels:
      app: znc-cluster-app
    name: znc-cluster-app
  spec:
    replicas: 1
    selector:
      app: znc-cluster-app
      deploymentconfig: znc-cluster-app
    strategy:
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          openshift.io/container.znc-cluster-app.image.entrypoint: '["/opt/znc-run/znc_runner.sh"]'
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: znc-cluster-app
          deploymentconfig: znc-cluster-app
      spec:
        containers:
        - image: nhripps/znc-cluster-app@sha256:cf496fa3969f044a3cbc1d43042adacb4f6653500922f65b8dd06178a9523acd
          imagePullPolicy: Always
          name: znc-cluster-app
          ports:
          - containerPort: 6697
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - znc-cluster-app
        from:
          kind: ImageStreamTag
          name: znc-cluster-app:latest
          namespace: myproject
      type: ImageChange
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: znc-cluster-app
    name: znc-cluster-app
  spec:
    ports:
    - name: 6697-tcp
      port: 6697
      protocol: TCP
      targetPort: 6697
    selector:
      app: znc-cluster-app
      deploymentconfig: znc-cluster-app
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: Route
  metadata:
    annotations:
      openshift.io/host.generated: "true"
    creationTimestamp: null
    labels:
      app: znc-cluster-app
    name: znc-cluster-app
  spec:
    port:
      targetPort: 6697-tcp
    tls:
      termination: passthrough
    to:
      kind: Service
      name: znc-cluster-app
      weight: 100
